swampVersion: 20260910.194957.0
initializedAt: "2026-07-17T02:11:06.886Z"
repoId: e46f92ff-737f-41b7-9d52-c141bb67a79c
tools:
  - opencode
gitignoreManaged: true
upgradedAt: "2026-09-10T22:15:42.104Z"
vault:
  type: "@svendowideit/systemd-creds"
  config:
    credstoreDir: ~/.config/credstore
trustedCollectives:
  - swamp
  - svendowideit
  - webframp
