/**
 * Test-factory harness: what to run inside a container, and how to read the
 * result.
 *
 * This module is pure. `buildHarnessScript` turns a typed {@link HarnessPlan}
 * into a POSIX `sh` script that installs swamp, registers the candidate
 * extension, and runs the requested phases; `parseHarnessResult` reads the JSON
 * the script leaves behind. The script is generated with each step written out
 * literally — the plan is known at build time — so the shell stays simple and
 * the interesting decisions are unit-testable.
 *
 * @module
 */

/** One fixture-driven method invocation. */
export interface FixtureRun {
  /** Model type to run, e.g. `@svendowideit/github-release-install`. */
  type: string;
  /** Method name, e.g. `check`. */
  method: string;
  /** Model instance name (auto-created on first use). */
  instance: string;
  /** Method/global inputs. */
  inputs: Record<string, string>;
  /** Continue even when this run fails. */
  allowFailure: boolean;
  /** When set, stdout/stderr must contain this substring to count as matched. */
  expectContains?: string;
}

/** Everything the in-container script needs to know. */
export interface HarnessPlan {
  /** swamp release tag, or empty/`latest` to resolve the latest release. */
  swampVersion: string;
  /** Repo path inside the container. */
  repoDir: string;
  /** Where the candidate extension is mounted (read-only). */
  extensionMount: string;
  /** Directory name to copy the extension into under `<repo>/extensions`. */
  extensionName: string;
  /** Declared model types from the extension manifest. */
  modelTypes: string[];
  /** Declared workflow names from the extension manifest. */
  workflows: string[];
  /** Phases to run, in order. */
  phases: HarnessPhase[];
  /** Fixture-driven method runs (only when `fixtures` is in `phases`). */
  fixtures: FixtureRun[];
  /** Base URL for release downloads (overridable for mirrors). */
  releaseBaseUrl: string;
  /** When true, assert systemd is running as PID 1 (`systemctl` works). */
  expectSystemd: boolean;
}

/** A named phase of the in-container test. */
export type HarnessPhase = "smoke" | "load" | "definitions" | "fixtures";

/** Default GitHub releases base URL. */
export const DEFAULT_RELEASE_BASE =
  "https://github.com/swamp-club/swamp/releases";

/** The path the script writes its JSON result to. */
export const RESULT_PATH = "/tf/result.json";

/**
 * The script's completion marker.
 *
 * The result file is written incrementally, so its mere existence does not mean
 * the run finished. This sentinel is written last (on both the success and the
 * install-failure path) and is what the caller waits for.
 */
export const DONE_PATH = "/tf/done";

/** Quote a value for safe interpolation into a POSIX shell single-quoted word. */
export function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Build the in-container `sh` script.
 *
 * The script records failures into the result JSON instead of aborting, so a
 * run always yields a report. Only installing swamp can make later phases
 * meaningless; when it fails the script writes a diagnosis and stops.
 */
export function buildHarnessScript(plan: HarnessPlan): string {
  const want = (p: HarnessPhase) => plan.phases.includes(p);
  const lines: string[] = [];
  const push = (...l: string[]) => lines.push(...l);

  push(
    "#!/bin/sh",
    "# Generated by @svendowideit/test-factory — do not edit.",
    "set -u",
    "export SWAMP_TELEMETRY_DISABLED=1",
    'export PATH="/usr/local/bin:$PATH"',
    "mkdir -p /tf /usr/local/bin",
    `RESULT=${shellQuote(RESULT_PATH)}`,
    `DONE=${shellQuote(DONE_PATH)}`,
    `rm -f "$DONE"`,
    `echo '{}' > "$RESULT"`,
    'log() { echo "[tf] $*" >&2; }',
    "",
    "# append a JSON value at a dotted path is overkill: each step merges a key.",
    "record() { # record <key> <json>",
    '  jq -c --arg k "$1" --argjson v "$2" \'.[$k] = $v\' "$RESULT" > /tf/r.tmp && mv /tf/r.tmp "$RESULT"',
    "}",
    "append() { # append <key> <json>  (to an array at <key>)",
    '  jq -c --arg k "$1" --argjson v "$2" \'.[$k] = ((.[$k] // []) + [$v])\' "$RESULT" > /tf/r.tmp && mv /tf/r.tmp "$RESULT"',
    "}",
    "",
  );

  // --- 1. install swamp -----------------------------------------------------
  push(
    "# --- 1. install swamp ---------------------------------------------------",
    "ARCH=$(uname -m)",
    'case "$ARCH" in',
    "  x86_64|amd64) SWAMP_ARCH=x86_64 ;;",
    "  aarch64|arm64) SWAMP_ARCH=aarch64 ;;",
    '  *) SWAMP_ARCH="$ARCH" ;;',
    "esac",
  );
  const version = plan.swampVersion && plan.swampVersion !== "latest"
    ? plan.swampVersion
    : "latest";
  const url = `${plan.releaseBaseUrl}/${
    version === "latest" ? "latest/download" : `download/${version}`
  }/swamp-linux-$SWAMP_ARCH`;
  push(
    `SWAMP_URL="${url}"`,
    'log "downloading swamp from $SWAMP_URL"',
    'if curl -fsSL -o /usr/local/bin/swamp "$SWAMP_URL"; then',
    "  chmod +x /usr/local/bin/swamp",
    "  swamp --version >/tmp/swamp-version.txt 2>/tmp/swamp-version.err",
    "  INSTALL_CODE=$?",
    "else",
    "  INSTALL_CODE=1",
    "  echo 'download failed' >/tmp/swamp-version.err",
    "fi",
    "SWAMP_VERSION_OUT=$(cat /tmp/swamp-version.txt 2>/dev/null || echo '')",
    'if [ "$INSTALL_CODE" -ne 0 ]; then',
    "  ERR=$(cat /tmp/swamp-version.err 2>/dev/null)",
    "  if [ -f /usr/local/bin/swamp ]; then",
    "    case \"$ERR\" in *'not found'*|'')",
    '      ERR="binary downloaded but cannot execute (the swamp binary is glibc-linked, so a musl-only distro such as Alpine cannot run it): $ERR" ;;',
    "    esac",
    "  fi",
    '  jq -n --arg e "$ERR" --arg v "$SWAMP_VERSION_OUT" \'{installOk:false, installError:$e, swampVersion:$v}\' > "$RESULT"',
    '  touch "$DONE"',
    '  log "swamp failed to install: $ERR"',
    "  exit 0",
    "fi",
    'record swampVersion "$(jq -Rn --arg v "$SWAMP_VERSION_OUT" \'$v\')"',
    "record installOk true",
    "",
  );

  if (plan.expectSystemd) {
    push(
      "# --- systemd check ------------------------------------------------------",
      "if command -v systemctl >/dev/null 2>&1 && systemctl is-system-running >/dev/null 2>&1; then",
      "  SYSTEMD_STATE=$(systemctl is-system-running 2>/dev/null || echo unknown)",
      '  record systemd "$(jq -Rn --arg v "$SYSTEMD_STATE" \'$v\')"',
      '  log "systemd=$SYSTEMD_STATE"',
      "else",
      '  record systemd "\\"not-running\\""',
      '  log "systemd is not running"',
      "fi",
      "",
    );
  }

  // --- 2. init repo + register the extension --------------------------------
  push(
    "# --- 2. init repo + register the extension ------------------------------",
    `REPO=${shellQuote(plan.repoDir)}`,
    `EXT_MOUNT=${shellQuote(plan.extensionMount)}`,
    `EXT_NAME=${shellQuote(plan.extensionName)}`,
    'mkdir -p "$REPO/extensions"',
    'cd "$REPO" || exit 1',
    "swamp init --tool none >/tmp/init.log 2>&1",
    'rm -rf "$REPO/extensions/$EXT_NAME"',
    'cp -r "$EXT_MOUNT" "$REPO/extensions/$EXT_NAME"',
    "",
  );
  if (want("smoke")) {
    push(
      'swamp extension source add "$REPO/extensions/$EXT_NAME" >/tmp/source-add.log 2>&1',
      "SOURCE_ADD_OK=$?",
      'if [ "$SOURCE_ADD_OK" -eq 0 ]; then record sourceAddOk true; else record sourceAddOk false; fi',
      "swamp doctor extensions --json >/tmp/doctor.json 2>/tmp/doctor.err",
      "DOCTOR_STATUS=$(jq -r '.overallStatus // \"unknown\"' /tmp/doctor.json 2>/dev/null || echo 'unparseable')",
      "DOCTOR_STATES=$(jq -c '[.aggregateState.aggregates[].stateDistribution] | add // {}' /tmp/doctor.json 2>/dev/null || echo '{}')",
      'record doctorStatus "$(jq -Rn --arg v "$DOCTOR_STATUS" \'$v\')"',
      'record doctorStates "$DOCTOR_STATES"',
      'log "doctor=$DOCTOR_STATUS"',
      "",
    );
  }
  if (want("load")) {
    push(
      "swamp model type search --json >/tmp/types.json 2>/dev/null || echo '{\"results\":[]}' >/tmp/types.json",
      "REGISTERED=$(jq -c '[.results[].normalized]' /tmp/types.json 2>/dev/null || echo '[]')",
      'record registeredTypes "$REGISTERED"',
      "",
    );
  }
  const modelTypesJson = JSON.stringify(plan.modelTypes);
  push(
    `MODEL_TYPES=${shellQuote(modelTypesJson)}`,
    'record modelTypes "$MODEL_TYPES"',
  );
  if (want("load")) {
    push(
      "MISSING='[]'",
      "for T in $(echo \"$MODEL_TYPES\" | jq -r '.[]'); do",
      '  if ! echo "$REGISTERED" | jq -e --arg t "$T" \'index($t)\' >/dev/null 2>&1; then',
      '    MISSING=$(echo "$MISSING" | jq -c --arg t "$T" \'. + [$t]\')',
      "  fi",
      "done",
      'record missingTypes "$MISSING"',
      "",
    );
  }

  // --- 3. definitions -------------------------------------------------------
  if (want("definitions")) {
    push(
      "# --- 3. definitions -----------------------------------------------------",
    );
    let idx = 0;
    for (const type of plan.modelTypes) {
      idx++;
      const name = `tf-def-${idx}`;
      push(
        `swamp model create ${shellQuote(type)} ${
          shellQuote(name)
        } >/tmp/def-${idx}.log 2>&1`,
        `if [ $? -eq 0 ]; then`,
        `  append definitions "$(jq -cn --arg t ${shellQuote(type)} --arg n ${
          shellQuote(name)
        } '{type:$t,name:$n,ok:true}')"`,
        `else`,
        `  append definitions "$(jq -cn --arg t ${shellQuote(type)} --arg n ${
          shellQuote(name)
        } --rawfile e /tmp/def-${idx}.log '{type:$t,name:$n,ok:false,error:($e|.[0:500])}')"`,
        `fi`,
      );
    }
    for (const wf of plan.workflows) {
      const slug = wf.replace(/[^a-zA-Z0-9]+/g, "_");
      push(
        `swamp workflow validate ${shellQuote(wf)} >/tmp/wf-${slug}.log 2>&1`,
        `if [ $? -eq 0 ]; then`,
        `  append workflows "$(jq -cn --arg w ${
          shellQuote(wf)
        } '{name:$w,ok:true,status:"valid"}')"`,
        `elif grep -qi "not found\\|No workflow" /tmp/wf-${slug}.log; then`,
        `  append workflows "$(jq -cn --arg w ${
          shellQuote(wf)
        } '{name:$w,ok:true,status:"absent"}')"`,
        `else`,
        `  append workflows "$(jq -cn --arg w ${
          shellQuote(wf)
        } --rawfile e /tmp/wf-${slug}.log '{name:$w,ok:false,status:"invalid",error:($e|.[0:500])}')"`,
        `fi`,
      );
    }
    push("");
  }

  // --- 4. fixtures ----------------------------------------------------------
  if (want("fixtures")) {
    push(
      "# --- 4. fixtures ---------------------------------------------------------",
    );
    plan.fixtures.forEach((f, i) => {
      const args = Object.entries(f.inputs)
        .map(([k, v]) => `--input ${shellQuote(`${k}=${v}`)}`)
        .join(" ");
      push(
        `swamp model ${shellQuote(f.type)} method run ${shellQuote(f.method)} ${
          shellQuote(f.instance)
        } ${args} >/tmp/fix-${i}.out 2>/tmp/fix-${i}.err`,
        `FIX_CODE=$?`,
        `FIX_OK=false`,
        `[ "$FIX_CODE" -eq 0 ] && FIX_OK=true`,
        `FIX_MATCHED=null`,
      );
      if (f.expectContains) {
        push(
          `if grep -qF -- ${
            shellQuote(f.expectContains)
          } /tmp/fix-${i}.out /tmp/fix-${i}.err 2>/dev/null; then`,
          `  FIX_MATCHED=true`,
          `else`,
          `  FIX_MATCHED=false`,
          `  FIX_OK=false`,
          `fi`,
        );
      }
      push(
        `[ ${shellQuote(String(f.allowFailure))} = "true" ] && FIX_OK=true`,
        `append fixtures "$(jq -cn --arg t ${shellQuote(f.type)} --arg m ${
          shellQuote(f.method)
        } --arg i ${
          shellQuote(f.instance)
        } --argjson c "$FIX_CODE" --argjson ok "$FIX_OK" --argjson mt "$FIX_MATCHED" --rawfile o /tmp/fix-${i}.out --rawfile e /tmp/fix-${i}.err '{type:$t,method:$m,instance:$i,code:$c,ok:$ok,matched:$mt,output:(($o+$e)|.[0:2000])}')"`,
      );
    });
    push("");
  }

  push('touch "$DONE"', 'log "done"', "exit 0", "");
  return lines.join("\n");
}

/** Parsed outcome of a harness run. */
export interface HarnessResult {
  installOk: boolean;
  installError?: string;
  swampVersion: string;
  doctorStatus: string;
  doctorStates: Record<string, number>;
  /** `systemctl is-system-running` output when systemd was expected. */
  systemd?: string;
  sourceAddOk: boolean;
  registeredTypes: string[];
  modelTypes: string[];
  missingTypes: string[];
  definitions: Array<{
    type: string;
    name: string;
    ok: boolean;
    error?: string;
  }>;
  workflows: Array<{
    name: string;
    ok: boolean;
    status: string;
    error?: string;
  }>;
  fixtures: Array<{
    type: string;
    method: string;
    instance: string;
    code: number;
    ok: boolean;
    matched: boolean | null;
    output: string;
  }>;
}

/** Parse the JSON result the harness script wrote. */
export function parseHarnessResult(text: string): HarnessResult {
  const parsed = JSON.parse(text) as Partial<HarnessResult>;
  return {
    installOk: parsed.installOk ?? false,
    installError: parsed.installError,
    swampVersion: parsed.swampVersion ?? "",
    doctorStatus: parsed.doctorStatus ?? "unknown",
    doctorStates: parsed.doctorStates ?? {},
    systemd: parsed.systemd,
    sourceAddOk: parsed.sourceAddOk ?? false,
    registeredTypes: parsed.registeredTypes ?? [],
    modelTypes: parsed.modelTypes ?? [],
    missingTypes: parsed.missingTypes ?? [],
    definitions: parsed.definitions ?? [],
    workflows: parsed.workflows ?? [],
    fixtures: parsed.fixtures ?? [],
  };
}

/**
 * Parse a fixtures file into {@link FixtureRun} entries.
 *
 * Accepts a JSON array, or a small YAML list where per-run inputs use a flat
 * `input.<key>: <value>` form (keeps the parser dependency-free):
 *
 * ```yaml
 * - type: "@acme/thing"
 *   method: check
 *   instance: fix-one
 *   input.repo: owner/name
 *   expectContains: ok
 * ```
 */
export function parseFixtures(text: string): FixtureRun[] {
  const trimmed = text.trim();
  if (trimmed.startsWith("[")) {
    const parsed = JSON.parse(trimmed) as Partial<FixtureRun>[];
    return parsed.map(normalizeFixture);
  }
  const runs: Array<Partial<FixtureRun> & { inputs?: Record<string, string> }> =
    [];
  let current:
    | (Partial<FixtureRun> & { inputs?: Record<string, string> })
    | null = null;
  for (const raw of trimmed.split("\n")) {
    const line = raw.replace(/\s+#.*$/, "");
    if (!line.trim()) continue;
    const item = /^\s*-\s+(.+)$/.exec(line);
    if (item) {
      current = { inputs: {} };
      runs.push(current);
      assignFixture(current, item[1]);
      continue;
    }
    const kv = /^\s+(.+)$/.exec(line);
    if (kv && current) assignFixture(current, kv[1]);
  }
  return runs.map(normalizeFixture);
}

/** Assign one `key: value` line onto a fixture being built. */
function assignFixture(
  target: Partial<FixtureRun> & { inputs?: Record<string, string> },
  line: string,
): void {
  const m = /^([\w.]+):\s*(.*)$/.exec(line);
  if (!m) return;
  const [, key, raw] = m;
  const value = raw.replace(/^["']|["']$/g, "");
  if (key.startsWith("input.")) {
    target.inputs = target.inputs ?? {};
    target.inputs[key.slice("input.".length)] = value;
  } else if (key === "allowFailure") {
    target.allowFailure = value === "true";
  } else if (key === "type" || key === "method" || key === "instance") {
    target[key] = value;
  } else if (key === "expectContains") {
    target.expectContains = value;
  }
}

/** Fill defaults for a partial fixture from a file. */
export function normalizeFixture(
  f: Partial<FixtureRun> & { inputs?: Record<string, string> },
): FixtureRun {
  return {
    type: f.type ?? "",
    method: f.method ?? "",
    instance: f.instance ?? "tf-fixture",
    inputs: f.inputs ?? {},
    allowFailure: f.allowFailure ?? false,
    expectContains: f.expectContains,
  };
}

const PHASE_ORDER: HarnessPhase[] = [
  "smoke",
  "load",
  "definitions",
  "fixtures",
];

/** Human-readable phase labels, in order. */
export function phaseLabel(phase: HarnessPhase): string {
  switch (phase) {
    case "smoke":
      return "smoke (install + doctor)";
    case "load":
      return "load (types register)";
    case "definitions":
      return "definitions (create + validate)";
    case "fixtures":
      return "fixtures (run methods)";
  }
}

/** Phase labels in canonical order. */
export function allPhaseLabels(): string[] {
  return PHASE_ORDER.map(phaseLabel);
}

/**
 * Evaluate a harness result against the phases a scenario requested.
 *
 * Returns a per-phase `ok` map plus the failing phases, so the report can show
 * exactly which layer broke (doctor, type registration, definition creation, or
 * a method run) rather than a single opaque pass/fail. A scenario marked
 * `expected: fail` passes precisely when the run does not succeed.
 */
export function evaluateResult(
  result: HarnessResult,
  phases: HarnessPhase[],
  expected: "pass" | "fail",
  expectSystemd = false,
): {
  phases: Array<{ phase: string; ok: boolean; detail: string }>;
  ok: boolean;
  errors: string[];
} {
  const out: Array<{ phase: string; ok: boolean; detail: string }> = [];
  const errors: string[] = [];
  const want = (p: HarnessPhase) => phases.includes(p);
  const expectPass = expected === "pass";

  let systemdOk = true;
  if (expectSystemd && result.installOk) {
    const state = result.systemd ?? "not-running";
    systemdOk = state === "running" || state === "degraded";
    out.push({ phase: "systemd", ok: systemdOk, detail: `systemd: ${state}` });
    if (!systemdOk && expectPass) errors.push(`systemd not running: ${state}`);
  }

  if (!result.installOk) {
    const detail = result.installError?.trim() ||
      "swamp could not be installed";
    // A scenario that *expects* failure passes when swamp is un-runnable.
    out.push({ phase: "smoke", ok: !expectPass, detail: `install: ${detail}` });
    if (want("smoke") && expectPass) errors.push(`install: ${detail}`);
    return { phases: out, ok: !expectPass, errors };
  }

  const smokeOk = result.sourceAddOk && result.doctorStatus === "pass";
  out.push({
    phase: "smoke",
    ok: smokeOk,
    detail: result.sourceAddOk
      ? `doctor: ${result.doctorStatus}`
      : "extension source could not be added",
  });
  if (want("smoke") && !smokeOk && expectPass) {
    errors.push(`smoke: doctor=${result.doctorStatus}`);
  }

  const loadOk = result.missingTypes.length === 0;
  out.push({
    phase: "load",
    ok: loadOk,
    detail: loadOk
      ? `${result.modelTypes.length} type(s) registered`
      : `missing types: ${result.missingTypes.join(", ")}`,
  });
  if (want("load") && !loadOk && expectPass) {
    errors.push(`load: missing ${result.missingTypes.join(", ")}`);
  }

  const failedDefs = result.definitions.filter((d) => !d.ok);
  const invalidWfs = result.workflows.filter((w) => !w.ok);
  const defsOk = failedDefs.length === 0 && invalidWfs.length === 0;
  out.push({
    phase: "definitions",
    ok: defsOk,
    detail: defsOk
      ? `${result.definitions.length} definition(s), ${result.workflows.length} workflow(s)`
      : [
        ...failedDefs.map((d) => `create ${d.type}: ${d.error ?? "failed"}`),
        ...invalidWfs.map((w) => `workflow ${w.name}: ${w.error ?? "invalid"}`),
      ].join("; "),
  });
  if (want("definitions") && !defsOk && expectPass) {
    errors.push(`definitions: ${out[out.length - 1].detail}`);
  }

  if (want("fixtures")) {
    const failedFix = result.fixtures.filter((f) => !f.ok);
    const fixOk = failedFix.length === 0 && result.fixtures.length > 0;
    const detail = result.fixtures.length === 0
      ? "no fixtures declared"
      : fixOk
      ? `${result.fixtures.length} fixture(s) ran`
      : failedFix.map((f) => `${f.type}/${f.method}: exit ${f.code}`).join(
        "; ",
      );
    out.push({ phase: "fixtures", ok: fixOk, detail });
    if (!fixOk && expectPass) errors.push(`fixtures: ${detail}`);
  }

  const ran = out.every((p) => p.ok);
  const ok = expectPass ? ran : !ran;
  return { phases: out, ok, errors };
}
