/**
 * Deployment-topology support for the test factory.
 *
 * A *topology* is how swamp is deployed around the extension:
 *  - `standalone` — one node, no server;
 *  - `serve`      — one node running `swamp serve` as an orchestrator;
 *  - `fleet`      — an orchestrator plus one or more worker nodes that enroll
 *                   and execute dispatched workflow steps.
 *
 * The orchestrator and each worker run in their own container. Workers share the
 * orchestrator's network namespace (`--network container:<orch>`) so they reach
 * the loopback-only serve socket without TLS — a real multi-process deployment
 * without the certificate dance.
 *
 * This module is pure: it builds the boot scripts and parses their output. The
 * container plumbing lives in the model.
 *
 * @module
 */
import { shellQuote } from "./harness.ts";

/** Orchestrator serve configuration. */
export interface ServeConfig {
  /** Repo directory inside the container. */
  repoDir: string;
  /** Port serve listens on (loopback). */
  port: number;
  /** Result directory shared with worker containers. */
  sharedDir: string;
  /** Enrollment tokens to mint, one per worker. */
  workerCount: number;
}

/** A shell script that starts `swamp serve` and waits for readiness. */
export function buildServeScript(cfg: ServeConfig): string {
  const url = `http://127.0.0.1:${cfg.port}`;
  return `#!/bin/sh
# Generated by @svendowideit/test-factory — start swamp serve.
set -u
export SWAMP_TELEMETRY_DISABLED=1
export PATH="/usr/local/bin:$PATH"
mkdir -p /usr/local/bin
cd ${shellQuote(cfg.repoDir)} || exit 1
mkdir -p ${shellQuote(cfg.sharedDir)}
nohup swamp serve --host 127.0.0.1 --port ${cfg.port} --auth-mode none \\
  > ${shellQuote(`${cfg.sharedDir}/serve.log`)} 2>&1 &
echo $! > ${shellQuote(`${cfg.sharedDir}/serve.pid`)}
i=0
while [ "$i" -lt 60 ]; do
  if curl -fsS ${shellQuote(`${url}/ready`)} >/dev/null 2>&1; then
    echo "SERVE_READY"
    exit 0
  fi
  i=$((i+1))
  sleep 1
done
echo "SERVE_TIMEOUT"
tail -30 ${shellQuote(`${cfg.sharedDir}/serve.log`)}
exit 1
`;
}

/** A shell script that mints worker enrollment tokens into the shared dir. */
export function buildTokenScript(cfg: ServeConfig): string {
  return `#!/bin/sh
# Generated by @svendowideit/test-factory — mint worker enrollment tokens.
set -u
export SWAMP_TELEMETRY_DISABLED=1
export PATH="/usr/local/bin:$PATH"
mkdir -p /usr/local/bin
cd ${shellQuote(cfg.repoDir)} || exit 1
mkdir -p ${shellQuote(cfg.sharedDir)}
: > ${shellQuote(`${cfg.sharedDir}/tokens.txt`)}
i=1
while [ "$i" -le ${cfg.workerCount} ]; do
  T=$(swamp worker token create "tf-w$i" --duration 1h --json 2>/dev/null | jq -r '.token // empty')
  if [ -n "$T" ]; then
    echo "$T" >> ${shellQuote(`${cfg.sharedDir}/tokens.txt`)}
  fi
  i=$((i+1))
done
wc -l < ${shellQuote(`${cfg.sharedDir}/tokens.txt`)}
`;
}

/** Arguments for a worker connect script. */
export interface WorkerConfig {
  /** Serve URL the worker dials. */
  url: string;
  /** Shared directory holding `tokens.txt`. */
  sharedDir: string;
  /** One-based worker index (selects its token line). */
  index: number;
  /** Scheduling labels the worker advertises. */
  labels: Record<string, string>;
  /** Release base URL the worker installs swamp from. */
  releaseBaseUrl: string;
  /** swamp release tag to install, or empty/`latest` for the latest. */
  swampVersion: string;
}

/**
 * A shell script that installs swamp, enrolls one worker, and blocks.
 *
 * A worker is a separate container with no swamp repo — just the binary — so it
 * installs swamp itself, exactly as a real worker host would. It then enrolls
 * with its enrollment token and reconnects forever, so the orchestrator sees a
 * stable worker for the life of the scenario.
 */
export function buildWorkerScript(cfg: WorkerConfig): string {
  const labelArgs = Object.entries(cfg.labels)
    .map(([k, v]) => `--label ${shellQuote(`${k}=${v}`)}`)
    .join(" ");
  const version = cfg.swampVersion && cfg.swampVersion !== "latest"
    ? cfg.swampVersion
    : "latest";
  const url = `${cfg.releaseBaseUrl}/${
    version === "latest" ? "latest/download" : `download/${version}`
  }/swamp-linux-$SWAMP_ARCH`;
  const log = shellQuote(`${cfg.sharedDir}/worker-${cfg.index}.log`);
  return `#!/bin/sh
# Generated by @svendowideit/test-factory — install swamp and enroll a worker.
set -u
export SWAMP_TELEMETRY_DISABLED=1
export PATH="/usr/local/bin:$PATH"
mkdir -p /usr/local/bin
LOG=${log}
case "$(uname -m)" in
  x86_64|amd64) SWAMP_ARCH=x86_64 ;;
  aarch64|arm64) SWAMP_ARCH=aarch64 ;;
  *) SWAMP_ARCH="$(uname -m)" ;;
esac
if ! command -v swamp >/dev/null 2>&1; then
  curl -fsSL -o /usr/local/bin/swamp "${url}" && chmod +x /usr/local/bin/swamp \
    || { echo "worker ${cfg.index}: swamp download failed" >> "$LOG"; exit 1; }
fi
TOKEN=$(sed -n "${cfg.index}p" ${shellQuote(`${cfg.sharedDir}/tokens.txt`)})
if [ -z "$TOKEN" ]; then
  echo "NO_TOKEN" >> "$LOG"
  exit 1
fi
echo "connecting worker ${cfg.index}" >> "$LOG"
while true; do
  swamp worker connect ${shellQuote(cfg.url)} --token "$TOKEN" \\
    --cache-dir ${shellQuote(`/work/wcache-${cfg.index}`)} ${labelArgs} \\
    >> "$LOG" 2>&1
  echo "worker ${cfg.index} disconnected, retrying" >> "$LOG"
  sleep 2
done
`;
}

/**
 * A probe workflow that runs a shell step and prints {@link REMOTE_MARKER}.
 *
 * With `place` the step carries a `pool: tf` label, so in a fleet it is
 * dispatched to an enrolled worker; without it the step runs on the
 * orchestrator (the `serve` topology's loopback path).
 */
export function buildProbeWorkflow(place: boolean): string {
  const placement = place
    ? `
labels:
  pool: tf`
    : "";
  return `id: 00000000-0000-4000-8000-000000000001
name: tf-probe
tags: {}${placement}
jobs:
  - name: main
    steps:
      - name: remote-echo
        task:
          type: model_method
          modelType: command/shell
          modelName: tf-probe-shell
          methodName: execute
          inputs:
            run: "echo TF_REMOTE_OK; hostname"
        dependsOn: []
        weight: 0
        allowFailure: false
    dependsOn: []
    weight: 0
version: 1
`;
}

/** A script that asks serve how many workers enrolled. */
export function buildWorkerCountScript(cfg: ServeConfig): string {
  return `#!/bin/sh
set -u
export PATH="/usr/local/bin:$PATH"
mkdir -p /usr/local/bin
cd ${shellQuote(cfg.repoDir)} || exit 1
swamp worker list --json 2>/dev/null | jq -r '.count // 0'
`;
}

/** A script that runs the probe through serve (placed or loopback). */
export function buildProbeRunScript(
  cfg: ServeConfig,
  place = true,
): string {
  const url = `ws://127.0.0.1:${cfg.port}`;
  return `#!/bin/sh
set -u
export SWAMP_TELEMETRY_DISABLED=1
export PATH="/usr/local/bin:$PATH"
mkdir -p /usr/local/bin
cd ${shellQuote(cfg.repoDir)} || exit 1
mkdir -p workflows
cat > workflows/workflow-tf-probe.yaml <<'YAML'
${buildProbeWorkflow(place)}
YAML
swamp workflow validate tf-probe >/dev/null 2>&1
swamp workflow run tf-probe --server ${shellQuote(url)} 2>&1
`;
}

/** Topology outcome recorded on a scenario result. */
export interface TopologyResult {
  /** Whether serve reported ready. */
  serveReady: boolean;
  /** Workers that enrolled (fleet only). */
  workersEnrolled: number;
  /** Workers requested (fleet only). */
  workersRequested: number;
  /** The dispatch probe succeeded and printed the remote marker. */
  dispatchOk: boolean;
  /** Serve/worker log tail, for diagnosis when something failed. */
  detail: string;
}

/** The marker the probe workflow prints on the worker. */
export const REMOTE_MARKER = "TF_REMOTE_OK";
